name: "🐛 Bug report (WebSpatial program)"
description: File a reproducible bug encountered while building with WebSpatial
title: "[BUG] <short summary>"
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug! Please fill in all required fields so triage is fast.
        Tip: attach a minimal repro repo or branch if possible.

  - type: checkboxes
    id: duplicates
    attributes:
      label: Duplicate check
      description: Please confirm you searched existing issues and the FAQ.
      options:
        - label: "I searched existing issues and discussions"
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One/two sentences describing the bug.
      placeholder: "Builder run crashes when launching on VisionOS simulator…"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected component(s)
      description: Select all that apply.
      multiple: true
      options:
        - "@webspatial/react-sdk"
        - "@webspatial/core-sdk"
        - "@webspatial/vite-plugin"
        - "@webspatial/builder (run/build)"
        - "@webspatial/platform-visionos"
        - "Example templates / starter"
        - "Docs / Guides"
        - "Other (describe below)"
    validations:
      required: true

  - type: input
    id: repro_link
    attributes:
      label: Minimal reproduction link
      description: Public repo/branch or zip link (ideally <100 lines diff).
      placeholder: "https://github.com/<org>/<repo>/tree/<branch>"

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps from a clean checkout.
      value: |
        1. git clone ... && npm ci
        2. npm run dev   (and)   XR_ENV=avp npm run dev:xr
        3. npx webspatial-builder run --base=http://localhost:5173
        4. Open VisionOS Simulator …
        5. Observe crash / error …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "App installs and opens a 2D window; model renders…"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "Builder prints ENOENT scandir /dist; Simulator shows black screen…"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - "S0 - Blocking (cannot proceed / demo-blocker)"
        - "S1 - Major (workaround exists but risky)"
        - "S2 - Minor (annoying; no data loss)"
        - "S3 - Cosmetic / Docs"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Environment"

  - type: input
    id: os
    attributes:
      label: Host OS & version
      placeholder: "macOS 14.6.1 (Apple Silicon or Intel?)"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: "node -v (e.g., 20.19.0 or 23.x)"
    validations:
      required: true

  - type: textarea
    id: packages
    attributes:
      label: WebSpatial & tooling versions
      description: Paste outputs so maintainers can reproduce exactly.
      value: |
        npm ls @webspatial/react-sdk @webspatial/core-sdk @webspatial/vite-plugin @webspatial/builder @webspatial/platform-visionos
        npm ls vite vite-plugin-html react react-dom
    validations:
      required: true

  - type: input
    id: xcode
    attributes:
      label: Xcode & visionOS SDK versions
      placeholder: "Xcode 16.x (build ####), visionOS SDK 2.x"
    validations:
      required: true

  - type: dropdown
    id: target
    attributes:
      label: Run target
      multiple: true
      options:
        - "Vision Pro device"
        - "VisionOS Simulator"
        - "Desktop browser (2D)"
        - "Mobile Safari / PWA"
    validations:
      required: true

  - type: input
    id: simulator_version
    attributes:
      label: Simulator version (if applicable)
      placeholder: "visionOS Simulator 2.x (device profile)"

  - type: input
    id: browser
    attributes:
      label: Browser & version (if 2D)
      placeholder: "Safari TP r###, Chrome 140, etc."

  - type: textarea
    id: env_vars
    attributes:
      label: Relevant env vars / commands
      description: Include any XR_ENV, __XR_ENV_BASE__, or builder flags used.
      placeholder: |
        XR_ENV=avp
        __XR_ENV_BASE__=http://localhost:5174
        npx webspatial-builder run --base=http://localhost:5173

  - type: textarea
    id: logs
    attributes:
      label: Logs & stack traces
      description: Paste terminal output (builder, dev server) and console logs.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / screen recordings
      description: Drag-and-drop images or short videos (Simulator/device captures).

  - type: textarea
    id: workarounds
    attributes:
      label: Tried workarounds
      description: Things you tried (e.g., downgrade vite to v6, use --legacy-peer-deps, clean node_modules).

  - type: textarea
    id: extra
    attributes:
      label: Extra context
      description: Anything else that might help (network constraints, corporate VPN, etc.).
